const os = require('os');
console.log(os.hostname())
console.log(os.platform())
console.log(os.release())
console.log(os.freemem())
console.log(os.uptime())
console.log(os.type())
console.log(os.arch())
console.log(os.homedir())
console.log(os.machine())
console.log(os.totalmem())
console.log(os.networkInterfaces())